Repository SigmundGranaas/forgero, pull requests merged in 2023-03, with the labels that each got.

#491 Added editorconfig
  .editorconfig
Labels: code quality

#489 Scrollable options menu
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/ForgeroConfigurationScreen.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/ForgeroModMenuIntegration.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/BooleanWidget.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/ConfigurationEntry.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/ConfigurationListWidget.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/DefaultEntry.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/IntInputOption.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/OptionEntryFactory.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/ResetButtonWidget.java
  forgero-fabric-compat/src/main/resources/assets/forgero/lang/en_us.json
Labels: enhancement

#492 Binding revisit
  forgero-extended/src/main/resources/assets/forgero/templates/textures/clumpy_pickaxe_head.png
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/axe_binding.png
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/axe_binding_reinforced.png
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/hoe_binding.png
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/hoe_binding_reinforced.png
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/pickaxe_binding.png
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/pickaxe_binding_reinforced.png
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/shovel_binding.png
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/shovel_binding_reinforced.png
Labels: texture, model

#490 Extended texture revisit
  forgero-extended/src/main/resources/assets/forgero/templates/textures/agile_sword_guard.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/agile_sword_guard_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/broad_pointed_axe_head.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/broad_pointed_axe_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/broadsword_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/broadsword_blade_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/clumpy_axe_head.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/clumpy_axe_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/clumpy_pickaxe_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/double_headed_axe_head.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/double_headed_axe_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/duelling_sword_guard.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/katana_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/katana_blade_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/kimiri_sword_guard.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/knife_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/knife_blade_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/pointy_axe_head.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/pointy_axe_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/pointy_pickaxe_head.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/pointy_pickaxe_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/pointy_shovel_head.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/pointy_shovel_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/rapier_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/reaper_head.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/reaper_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/saber_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/saber_blade_grip.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/saber_blade_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/scimitar_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/scimitar_blade_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/serrated_sword_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/serrated_sword_blade_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/shortsword_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/shortsword_blade_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/slanted_sword_blade.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/slanted_sword_blade_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/square_shovel_head.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/square_shovel_head_tip_reinforcement.png
  forgero-extended/src/main/resources/assets/forgero/templates/textures/tsuba_sword_guard.png
  forgero-extended/src/main/resources/assets/forgero/textures/item/clumpy_pickaxe_head.png
  forgero-extended/src/main/resources/data/forgero/packs/hoe-additions/models/reaper_head.json
  forgero-extended/src/main/resources/data/forgero/packs/pickaxe-additions/models/mastercrafted_pickaxe_head.json
  forgero-extended/src/main/resources/data/forgero/packs/pickaxe-additions/models/ore_mining_pickaxe_head.json
  forgero-extended/src/main/resources/data/forgero/packs/pickaxe-additions/models/path_mining_pickaxe_head.json
  forgero-vanilla/src/main/resources/assets/forgero/templates/textures/hoe_head.png
Labels: enhancement, texture

#518 [WIP] 344 pattern mining tools have improper directional values when facing up or down
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/property/v2/cache/ContainsFeatureCache.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/property/v2/feature/PropertyData.java
  forgero-extended/src/main/resources/data/forgero/packs/axe-additions/schematic/tree_feller_head.json
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/AbstractBlockMixin.java
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/PlayerInteractionManagerMixin.java
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/PlayerServerInteractionManagerMixin.java
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/WorldRenderBlockBreakingMixin.java
  forgero-fabric/src/main/resources/assets/forgero/lang/en_us.json
  forgero-fabric/src/test/java/com/sigmundgranaas/forgerofabric/gametest/BlockSelectionTest.java
  forgero-fabric/src/test/resources/fabric.mod.json
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/item/DynamicAttributeItem.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/BlockBreakingHandler.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/BlockBreakingStrategy.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/PatternBreakingStrategy.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/SoulHandler.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/ToolBlockHandler.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/VeinMiningStrategy.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/BlockBreakingEfficiencyTarget.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/BlockHandlerCache.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/BlockHandlerFactory.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/BlockUtils.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/ToolBlockHandler.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/hardness/HardnessProvider.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/hardness/MultiBlockHardnessCalculator.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/hardness/SingleBlockHardnessProvider.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/readme.md
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/selector/BlockSelectionUtils.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/selector/BlockSelector.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/selector/CachedSelector.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/selector/ColumnSelector.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/selector/FilteredSelector.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/selector/PatternSelector.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/block/selector/RadiusVeinSelector.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/tooltip/v2/feature/FeatureWriterSelector.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/utils/DebugUtil.java
Labels: bug, translation

#532 Mythic metals update
  forgero-compat/src/main/resources/assets/forgero/templates/materials/adamantite.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/aquarium.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/banglum.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/bronze.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/carmot.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/celestium.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/durasteel.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/hallowed.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/kyber.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/metallurgium.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/midasg_old.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/mythril.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/orichalcum.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/osmium.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/palladium.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/prometheum.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/quadrillum.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/runite.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/star_platinum.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/steel.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/stormyx.png
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/adamantite.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/aquarium.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/banglum.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/bronze.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/carmot.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/celestium.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/durasteel.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/hallowed.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/kyber.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/metallurgium.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/mythril.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/orichalcum.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/osmium.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/palladium.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/prometheum.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/quadrillum.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/runite.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/silver.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/star_platinum.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/steel.json
  forgero-compat/src/main/resources/data/forgero/packs/mythic-metals/material/stormyx.json
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/configuration/ForgeroConfiguration.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/texture/V2/TextureGenerator.java
Labels: compatibility

#541 Tweak readme, add `CONTRIBUTING.md` and `CONTRIBUTORS.md`
  CONTRIBUTING.md
  CONTRIBUTORS.md
  README.md
Labels: documentation

#547 fix: remove category tag on composite attribute
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-wood-variants/material/acacia.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-wood-variants/material/birch.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-wood-variants/material/dark_oak.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-wood-variants/material/jungle.json
Labels: bug
