Repository SigmundGranaas/forgero, pull requests merged in 2023-02, with the labels that each got.

#467 AE2 Materials
  forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  forgero-compat/src/main/resources/assets/forgero/templates/materials/certus_quartz.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/fluix.png
  forgero-compat/src/main/resources/assets/forgero/templates/materials/nether_quartz.png
  forgero-compat/src/main/resources/data/forgero/packs/ae2/default.json
  forgero-compat/src/main/resources/data/forgero/packs/ae2/material/certus-quartz.json
  forgero-compat/src/main/resources/data/forgero/packs/ae2/material/fluix.json
  forgero-compat/src/main/resources/data/forgero/packs/ae2/material/nether-quartz.json
  forgero-compat/src/main/resources/data/forgero/packs/ae2/package.json
  forgero-fabric-compat/build.gradle
Labels: compatibility

#463 Refactor veinmining code
  forgero-extended/src/main/resources/data/forgero/packs/axe-additions/schematic/tree_chopper_head.json
  forgero-extended/src/main/resources/data/forgero/packs/axe-additions/schematic/tree_feller_head.json
  forgero-extended/src/main/resources/data/forgero/packs/shovel-additions/schematic/grave_digger_head.json
  forgero-extended/src/main/resources/data/forgero/tags/blocks/vein_mining_dirt.json
  forgero-extended/src/main/resources/data/forgero/tags/blocks/vein_mining_logs.json
  forgero-extended/src/main/resources/data/forgero/tags/blocks/vein_mining_sand.json
  forgero-fabric-compat/build.gradle
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/BlockBreakingHandler.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/BlockBreakingStrategy.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/PatternBreakingStrategy.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/ToolBlockHandler.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/toolhandler/VeinMiningStrategy.java
Labels: bug, enhancement

#487 Fixed non-composite parts
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/resources/dynamic/PartTypeTagGenerator.java
  forgero-fabric/src/test/java/com/sigmundgranaas/forgerofabric/gametest/UpgradeTest.java
  forgero-vanilla/src/main/resources/data/forgero/packs/forgero-scrappy-variants/model/binding.json
  forgero-vanilla/src/main/resources/data/forgero/packs/forgero-scrappy-variants/part/scrappy-leather-binding.json
  forgero-vanilla/src/main/resources/data/forgero/packs/forgero-scrappy-variants/part/string-binding.json
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/tooltip/StateWriter.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/tooltip/v2/section/AttributeSectionWriter.java
Labels: bug
