Repository SigmundGranaas/forgero, pull requests merged in 2023-07, with the labels that each got.

#651 Added checks to ensure the upgrade in crafting table picks the right recipe
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/recipe/customrecipe/StateUpgradeShapelessRecipe.java
Labels: bug, crash

#654 Deleted old schematic files
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/axehead_schematic_base.png
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/binding_schematic_base.png
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/handle_schematic_base.png
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/hoehead_schematic_base.png
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/pickaxehead_schematic_base.png
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/pummel_schematic.png
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/shovelhead_schematic_base.png
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/sword_guard_schematic.png
  content/forgero-vanilla/src/main/resources/assets/forgero/textures/item/swordhead_schematic_base.png
Labels: code quality

#661 Fix occasional `null` config crash
  content/forgero-extended/src/test/java/com/sigmundgranaas/forgeroforge/test/util/ForgeroPipeLineSetup.java
  content/forgero-vanilla/src/test/java/com/sigmundgranaas/forgeroforge/test/util/ForgeroPipeLineSetup.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/ForgeroConfigurationScreen.java
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroInitializer.java
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/initialization/datareloader/DataPipeLineReloader.java
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgerofabric/nbt/v2/StateNbtConversionTest.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/configuration/ForgeroConfigurationLoader.java
Labels: bug, crash, cherrypick
