Repository SigmundGranaas/forgero, pull requests merged in 2023-01, with the labels that each got.

#300 Update zh_cn.json
  forgero-compat/src/main/resources/assets/forgero/lang/zh_cn.json
Labels: translation

#301 Update zh_cn.json
  forgero-extended/src/main/resources/assets/forgero/lang/zh_cn.json
Labels: translation

#302 Update zh_cn.json
  forgero-vanilla/src/main/resources/assets/forgero/lang/zh_cn.json
Labels: translation

#326 Mod Menu integration
  build.gradle
  forgero-compat/src/main/resources/assets/forgero/icon.png
  forgero-compat/src/main/resources/fabric.mod.json
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/configuration/BuildableConfiguration.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/configuration/DefaultConfiguration.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/configuration/ForgeroConfiguration.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/configuration/ForgeroConfigurationData.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/configuration/ForgeroConfigurationLoader.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/resource/PipelineBuilder.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/resource/ResourcePipeline.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/settings/ForgeroSettings.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/settings/SettingsLoader.java
  forgero-core/src/main/resources/assets/forgero/icon.png
  forgero-core/src/main/resources/fabric.mod.json
  forgero-extended/src/main/resources/assets/forgero/icon.png
  forgero-extended/src/main/resources/fabric.mod.json
  forgero-fabric-compat/build.gradle
  forgero-fabric-compat/gradle.properties
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/ModMenuInitMixin.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/ForgeroConfigurationScreen.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/ForgeroModMenuIntegration.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/BooleanWidget.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/ListWidget.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/ResetButtonWidget.java
  forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/modmenu/gui/TextWidget.java
  forgero-fabric-compat/src/main/resources/assets/forgero/icon.png
  forgero-fabric-compat/src/main/resources/assets/forgero/lang/en_us.json
  forgero-fabric-compat/src/main/resources/fabric.mod.json
  forgero-fabric-compat/src/main/resources/forgero-fabric-compat.mixins.json
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroInitializer.java
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/client/ForgeroClient.java
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/RecipeManagerMixin.java
  forgero-fabric/src/main/java/com/sigmundgranaas/forgero/fabric/resources/dynamic/RepairKitResourceGenerator.java
  forgero-fabric/src/main/resources/fabric.mod.json
  forgero-forge/src/main/java/com/sigmundgranaas/forgero/forge/ForgeroInitializer.java
  forgero-forge/src/main/java/com/sigmundgranaas/forgero/forge/pack/ForgePackFinder.java
  forgero-structures/src/main/resources/assets/forgero/icon.png
  forgero-structures/src/main/resources/fabric.mod.json
  forgero-vanilla/src/main/resources/assets/forgero/icon.png
  forgero-vanilla/src/main/resources/fabric.mod.json
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/item/DynamicItems.java
  minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/recipe/implementation/generator/RepairKitRecipeGenerator.java
  minecraft-common/src/main/resources/assets/forgero/icon.png
  minecraft-common/src/main/resources/fabric.mod.json
Labels: documentation, Improvement, compatability

#327 Forgero 0.11 Gems & Souls
  build.gradle
  changelog.md
  forgero-compat/build.gradle
  forgero-core/build.gradle
  forgero-extended/build.gradle
  forgero-fabric-compat/build.gradle
  forgero-fabric/build.gradle
  forgero-forge/build.gradle
  forgero-structures/build.gradle
  forgero-vanilla/build.gradle
  gradle.properties
  minecraft-common/build.gradle
Labels: Improvement, New Feature, update, Creature
