Repository SigmundGranaas/forgero, pull requests merged in 2024-08, with the labels that each got.

#1002 [Compat]: Let's Do Blooming Nature Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/bloomingnature/chestnut.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/bloomingnature/fan_palm.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/bloomingnature/laterit.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/bloomingnature/swamp_cypress.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/bloomingnature/swamp_oak.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/bloomingnature/travertin.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/aspen.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/baobab.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/ebony.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/fir.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/larch.png
  content/forgero-compat/src/main/resources/data/forgero/packs/bloomingnature/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bloomingnature/material/chestnut.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bloomingnature/material/fan_palm.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bloomingnature/material/laterit.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bloomingnature/material/swamp_cypress.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bloomingnature/material/swamp_oak.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bloomingnature/material/travertin.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bloomingnature/package.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/aspen.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/baobab.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/ebony.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/fir.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/larch.json
  fabric/build.gradle
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroCompatInitializer.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/BloomingNature.java
Labels: new feature, texture, compatibility, balancing

#1000 [Compat]: Fruitful Fun Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/fruitfulfun/citrus.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/fruitfulfun/redlove.png
  content/forgero-compat/src/main/resources/data/forgero/packs/fruitfulfun/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/fruitfulfun/material/citrus.json
  content/forgero-compat/src/main/resources/data/forgero/packs/fruitfulfun/material/redlove.json
  content/forgero-compat/src/main/resources/data/forgero/packs/fruitfulfun/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1006 [Compat]: Let's Do Beachparty
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/palm.png
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/palm.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/package.json
  fabric/build.gradle
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroCompatInitializer.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/BeachParty.java
Labels: new feature, texture, compatibility, balancing

#1008 [Compat]: Let's Do Nethervinery Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/nethervinery/obsidian_stem.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/nethervinery/reinforced_crimson.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/nethervinery/reinforced_warped.png
  content/forgero-compat/src/main/resources/data/forgero/packs/nethervinery/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/nethervinery/material/obsidian_stem.json
  content/forgero-compat/src/main/resources/data/forgero/packs/nethervinery/material/reinforced_crimson.json
  content/forgero-compat/src/main/resources/data/forgero/packs/nethervinery/material/reinforced_warped.json
  content/forgero-compat/src/main/resources/data/forgero/packs/nethervinery/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#988 [Patch]: More basic recipe generators fixed for compats
  content/forgero-extended/src/main/resources/data/forgero/recipe_generators/basic_short_sword_blade.json
  content/forgero-vanilla/src/main/resources/data/forgero/recipe_generators/simple_wood/basic_hoe_head.json
  content/forgero-vanilla/src/main/resources/data/forgero/recipe_generators/simple_wood/basic_sword_guard.json
  fabric/modules/bows/src/main/resources/data/forgero/recipe_generators/simple_wooden_bow.json
Labels: bug, compatibility

#989 [Patch]: Fixed up some stone palettes
  content/forgero-vanilla/src/main/resources/assets/forgero/templates/materials/andesite.png
  content/forgero-vanilla/src/main/resources/assets/forgero/templates/materials/calcite.png
  content/forgero-vanilla/src/main/resources/assets/forgero/templates/materials/cobblestone.png
  content/forgero-vanilla/src/main/resources/assets/forgero/templates/materials/diorite.png
  content/forgero-vanilla/src/main/resources/assets/forgero/templates/materials/end_stone.png
  content/forgero-vanilla/src/main/resources/assets/forgero/templates/materials/nether_quartz.png
  content/forgero-vanilla/src/main/resources/assets/forgero/templates/materials/stone.png
Labels: texture

#991 [Patch]: Fixed some small bits in the new modonomicon book
  fabric/forgero-fabric-compat/gradle.properties
  fabric/forgero-fabric-core/src/main/resources/assets/forgero/lang/en_us.json
  fabric/forgero-fabric-core/src/main/resources/assets/forgero/textures/gui/tooltip.png
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/categories/getting_started.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/categories/schematics.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/categories/upgrading.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/getting_started/handle.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/getting_started/head.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/binding.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/cosmetic.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/gems.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/grip.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/offensive.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/pommel.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/reinforcement.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/slots.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/stats.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/trinket.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/utility.json
  fabric/forgero-fabric-core/src/main/resources/data/forgero/modonomicon/books/guidebook/entries/upgrading/weight.json
Labels: documentation

#1001 [Patch]: Added Create Tags
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/brass.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/limestone.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/zinc.png
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/brass.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/limestone.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/zinc.json
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroCompatInitializer.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/Create.java
Labels: enhancement, compatibility

#1005 [Patch]: Update `CONTRIBUTORS.md`
  CONTRIBUTORS.md
  content/forgero-compat/src/main/resources/fabric.mod.json
  content/forgero-extended/src/main/resources/fabric.mod.json
  content/forgero-structures/src/main/resources/fabric.mod.json
  content/forgero-vanilla/src/main/resources/fabric.mod.json
  fabric/forgero-fabric-compat/src/main/resources/fabric.mod.json
  fabric/forgero-fabric-core/src/main/resources/fabric.mod.json
  fabric/minecraft-common/src/main/resources/fabric.mod.json
  fabric/modules/bows/src/main/resources/fabric.mod.json
  fabric/modules/trade/src/main/resources/fabric.mod.json
  fabric/src/main/resources/fabric.mod.json
  forgero-core/src/main/resources/fabric.mod.json
Labels: documentation

#986 [Patch]: Added StatusEffect handler tests
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgero/fabric/gametest/HitHandlerTests.java
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgero/fabric/gametest/handler/StatusEffectTest.java
  fabric/minecraft-common/build.gradle
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/handler/targeted/onHitEntity/StatusEffectHandler.java
  fabric/minecraft-common/src/test/java/com/sigmundgranaas/forgero/minecraft/common/handler/Bootstrapped.java
  fabric/minecraft-common/src/test/java/com/sigmundgranaas/forgero/minecraft/common/handler/StatusEffectHandlerTest.java
Labels: new feature, testing

#965 [Feature]: World predicates
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/initialization/ForgeroPreInit.java
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgero/fabric/gametest/EntityPredicateTest.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/api/v0/predicate/Registries.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/AbstractMapCodec.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/DimensionPredicate.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/KeyCodec.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/LocationPredicate.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/Provider.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/SpecificationBackedPredicateCodec.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/block/Adapters.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/block/BlockPredicateMatcher.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/block/BlockPredicates.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/AdapterCodec.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/CodecUtils.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/GroupEntry.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/KeyBasedRegistryBackedMapCodec.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/KeyPair.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/KeyPairCodec.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/KeyProvider.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/PredicateAdapter.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/SpecificationBackedPredicateCodec.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/codecs/SpecificationRegistry.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/entity/EntityAdapter.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/entity/EntityFlagPredicates.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/entity/EntityPredicate.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/error/MissingFieldErrorHandler.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/error/PredicateErrorHandler.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/error/TypeFieldErrorHandler.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/error/WarningMessageBuilder.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/flag/FlagGroupCodec.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/flag/FlagGroupPredicate.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/flag/FlagPredicateInstance.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/flag/PredicatePair.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/util/AnsiColors.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/util/JsonUtils.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/world/Adapters.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/world/BiomePosPredicate.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/world/DimensionPredicate.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/world/WorldPredicate.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/predicate/world/XYZPredicate.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/util/StringSimilarity.java
Labels: new feature

#967 [Patch]: Fixed broken random predicate
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/initialization/ForgeroPreInit.java
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgero/fabric/gametest/PredicateTests.java
  fabric/forgero-fabric-core/src/test/resources/fabric.mod.json
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/match/predicate/RandomPredicate.java
  fabric/minecraft-common/src/test/java/com/sigmundgranaas/forgero/minecraft/common/predicate/RandomPredicate.java
Labels: bug

#996 [Compat]: Tech Reborn
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/bronze.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/silver.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/advanced_alloy.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/carbon_fiber.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/carbon_mesh.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/peridot.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/red_garnet.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/refined_iron.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/rubber.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/rubber_planks.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/ruby.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/sap.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/sapphire.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/synthetic_redstone.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/tungstensteel.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/yellow_garnet.png
  content/forgero-compat/src/main/resources/data/forgero/packs/common/package.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/advanced_alloy.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/carbon_fiber.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/carbon_mesh.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/peridot.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/red_garnet.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/refined_iron.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/rubber.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/rubber_planks.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/ruby.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/sap.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/sapphire.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/synthetic_redstone.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/tungstensteel.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/yellow_garnet.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/package.json
  fabric/build.gradle
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroCompatInitializer.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/TechReborn.java
Labels: new feature, texture, compatibility, balancing

#999 [Compat]: Create: Garnished Additions Compatibility (Another addon to Garnished.)
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/garnished_additions/ethereal.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/garnished_additions/ethereal_roots.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/garnished_additions/nutium.png
  content/forgero-compat/src/main/resources/data/forgero/packs/garnished_additions/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/garnished_additions/material/ethereal.json
  content/forgero-compat/src/main/resources/data/forgero/packs/garnished_additions/material/ethereal_roots.json
  content/forgero-compat/src/main/resources/data/forgero/packs/garnished_additions/material/nutium.json
  content/forgero-compat/src/main/resources/data/forgero/packs/garnished_additions/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1004 [Compat]. Fruitful Fun
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/fruitfulfun/citrus.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/fruitfulfun/redlove.png
  content/forgero-compat/src/main/resources/data/forgero/packs/fruitfulfun/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/fruitfulfun/material/citrus.json
  content/forgero-compat/src/main/resources/data/forgero/packs/fruitfulfun/material/redlove.json
  content/forgero-compat/src/main/resources/data/forgero/packs/fruitfulfun/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1007 [Compat]: Lets Do Beach Party
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/palm.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/package.json
  fabric/build.gradle
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroCompatInitializer.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/BeachParty.java
Labels: new feature, texture, compatibility, balancing

#1013 [Compat]: Letsdo Vinery
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/vinery/dark_cherry.png
  content/forgero-compat/src/main/resources/data/forgero/packs/vinery/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/vinery/material/dark_cherry.json
  content/forgero-compat/src/main/resources/data/forgero/packs/vinery/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1015 [Compat]: Gardens of the Dead
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/gardens_of_the_dead/soulblight.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/gardens_of_the_dead/soulblight_fungus.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/gardens_of_the_dead/whistlecane.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/gardens_of_the_dead/whistlecane_planks.png
  content/forgero-compat/src/main/resources/data/forgero/packs/gardens_of_the_dead/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/gardens_of_the_dead/material/soulblight.json
  content/forgero-compat/src/main/resources/data/forgero/packs/gardens_of_the_dead/material/soulblight_fungus.json
  content/forgero-compat/src/main/resources/data/forgero/packs/gardens_of_the_dead/material/whistlecane.json
  content/forgero-compat/src/main/resources/data/forgero/packs/gardens_of_the_dead/material/whistlecane_planks.json
  content/forgero-compat/src/main/resources/data/forgero/packs/gardens_of_the_dead/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1021 [Compat]: Ribbits
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ribbits/lush_lily_pad.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ribbits/mossy_oak.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ribbits/toadstool.png
  content/forgero-compat/src/main/resources/data/forgero/packs/ribbits/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ribbits/material/lush_lily_pad.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ribbits/material/mossy_oak.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ribbits/material/toadstool.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ribbits/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1022 [Compat]: Dragonloot
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/dragonloot/dragon_scale.png
  content/forgero-compat/src/main/resources/data/forgero/packs/dragonloot/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/dragonloot/material/dragon_scale_2.json
  content/forgero-compat/src/main/resources/data/forgero/packs/dragonloot/package.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/type/material/tool_material.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1016 [Compat]: Mythic Metals Decorations
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/decorations/hydrargym.png
  content/forgero-compat/src/main/resources/data/forgero/packs/mythic-metals-decoration/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/mythic-metals-decoration/material/hydrargym.json
  content/forgero-compat/src/main/resources/data/forgero/packs/mythic-metals-decoration/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1017 [Patch]: Fixed wrong modifiers in some files
  content/forgero-compat/src/main/resources/data/forgero/packs/betterend/material/gelatine.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/material-baseline-variants/crystal_base.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/material-baseline-variants/goo_base.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/material-baseline-variants/hard_plant_base.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/material-baseline-variants/pearl_base.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/material-baseline-variants/scale_base.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/material-baseline-variants/soft_plant_base.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/secondary-materials/hard-material-variants/hard-plant-material-variants/crimson_fungus.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/secondary-materials/hard-material-variants/hard-plant-material-variants/popped_chorus_fruit.json
  content/forgero-vanilla/src/main/resources/data/forgero/packs/minecraft-material/secondary-materials/hard-material-variants/hard-plant-material-variants/red_mushroom.json
Labels: bug

#1035 [Patch]: Corrected compatibility slugs
  fabric/build.gradle
Labels: bug, important, ci/cd

#1038 [Compat]: Enderite Mod Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/enderitemod/enderite.png
  content/forgero-compat/src/main/resources/data/forgero/packs/enderitemod/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/enderitemod/material/enderite.json
  content/forgero-compat/src/main/resources/data/forgero/packs/enderitemod/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1043 [Compat]: Galosphere Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/galosphere/allurite_shard.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/galosphere/bowl_lichen.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/galosphere/cured_membrane.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/galosphere/lumiere_shard.png
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/silver.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/material/allurite_shard.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/material/bowl_lichen.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/material/cured_membrane.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/material/lumiere_shard.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/package.json
  fabric/build.gradle
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroCompatInitializer.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/Galosphere.java
Labels: new feature, texture, compatibility, balancing

#1047 [Compat]: End's Phantasm Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/phantasm/crystal_block.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/phantasm/crystal_shard.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/phantasm/fallen_star.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/phantasm/oblivine.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/phantasm/pream.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/phantasm/void_crystal_block.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/phantasm/void_crystal_shard.png
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/material/crystal_block.json
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/material/crystal_shard.json
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/material/fallen_star.json
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/material/oblivine.json
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/material/pream.json
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/material/void_crystal_block.json
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/material/void_crystal_shard.json
  content/forgero-compat/src/main/resources/data/forgero/packs/phantasm/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1046 [Compat]: Eldritch End Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/eldritch_end/aberration_heart.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/eldritch_end/aberration_limb.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/eldritch_end/etyr.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/eldritch_end/primordial.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/eldritch_end/spire_stone.png
  content/forgero-compat/src/main/resources/data/forgero/packs/eldritch_end/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/eldritch_end/material/aberration_heart.json
  content/forgero-compat/src/main/resources/data/forgero/packs/eldritch_end/material/aberration_limb.json
  content/forgero-compat/src/main/resources/data/forgero/packs/eldritch_end/material/etyr.json
  content/forgero-compat/src/main/resources/data/forgero/packs/eldritch_end/material/primordial.json
  content/forgero-compat/src/main/resources/data/forgero/packs/eldritch_end/material/spire_stone.json
  content/forgero-compat/src/main/resources/data/forgero/packs/eldritch_end/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1041 [Compat]: Beneath The Wetlands Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/wetlands/bog_iron.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/wetlands/elder_gear_golem_heart.png
  content/forgero-compat/src/main/resources/data/forgero/packs/wetlands/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/wetlands/material/bog_iron.json
  content/forgero-compat/src/main/resources/data/forgero/packs/wetlands/material/elder_gear_golem_heart.json
  content/forgero-compat/src/main/resources/data/forgero/packs/wetlands/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1052 [Patch] Added and fixed redundant tags
  content/forgero-compat/src/main/resources/data/forgero/packs/common/package.json
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/CommonTags.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/Create.java
Labels: enhancement

#966 [Patch]: Fixed issues with teleport handler and added some features
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgero/fabric/gametest/TeleportHandlerTest.java
  fabric/forgero-fabric-core/src/test/resources/fabric.mod.json
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/handler/entity/TeleportHandler.java
Labels: bug, code quality, new feature

#970 [Patch]: Improved throwing handler
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgero/fabric/gametest/handler/StatusEffectTest.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/handler/use/ThrowableHandler.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/handler/use/ThrowableItem.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/handler/use/ThrowableItemRenderer.java
Labels: enhancement, code quality

#1034 [Patch]: Added tests for explosion damage
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgero/fabric/gametest/ExplosionHandlerTests.java
  fabric/forgero-fabric-core/src/test/resources/fabric.mod.json
Labels: testing

#1039 [Compat]: Spelunkery Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/button_mushroom.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/cinnabar.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/crimini.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/inkcap_mushroom.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/milly_bubcap.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/mushgloom.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/nephrite.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/phosphor_fungus.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/portabella.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/raw_magnetite.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/tangle_roots.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/spelunkery/white_inkcap_mushroom.png
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/button_mushroom.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/cinnabar.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/crimini.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/inkcap_mushroom.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/milly_bubcap.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/mushgloom.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/nephrite.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/phosphor_fungus.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/portabella.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/raw_magnetite.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/tangle_roots.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/material/white_inkcap_mushroom.json
  content/forgero-compat/src/main/resources/data/forgero/packs/spelunkery/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1053 [Compat] Enderite
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/enderitemod/enderite.png
  content/forgero-compat/src/main/resources/data/forgero/packs/enderitemod/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/enderitemod/material/enderite.json
  content/forgero-compat/src/main/resources/data/forgero/packs/enderitemod/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1054 [Compat] Galosphere
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/galosphere/allurite_shard.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/galosphere/bowl_lichen.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/galosphere/cured_membrane.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/galosphere/lumiere_shard.png
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/silver.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/package.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/material/allurite_shard.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/material/bowl_lichen.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/material/cured_membrane.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/material/lumiere_shard.json
  content/forgero-compat/src/main/resources/data/forgero/packs/galosphere/package.json
  fabric/build.gradle
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroCompatInitializer.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/CommonTags.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/Galosphere.java
Labels: new feature, texture, compatibility, balancing

#1042 [Compat]: Bountiful Fares Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/bountifulfares/feldspar.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/bountifulfares/hoary.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/common/walnut.png
  content/forgero-compat/src/main/resources/data/forgero/packs/bountifulfares/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bountifulfares/material/feldspar.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bountifulfares/material/hoary.json
  content/forgero-compat/src/main/resources/data/forgero/packs/bountifulfares/package.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/walnut.json
  fabric/build.gradle
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/ForgeroCompatInitializer.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/BountifulFares.java
  fabric/forgero-fabric-compat/src/main/java/com/sigmundgranaas/forgero/fabric/tags/Ecologics.java
Labels: new feature, texture, compatibility, balancing

#1040 [Compat]: Edenring Reforked Compatibility
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/edenring/auritis.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/edenring/balloon_mushroom.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/edenring/balloon_mushroom_small.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/edenring/brain_tree.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/edenring/eden_vine.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/edenring/gravilite.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/edenring/pulse_tree.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/edenring/tall_balloon_mushroom.png
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/material/auritis.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/material/balloon_mushroom.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/material/balloon_mushroom_small.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/material/brain_tree.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/material/eden_vine.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/material/gravilite.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/material/pulse_tree.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/material/tall_balloon_mushroom.json
  content/forgero-compat/src/main/resources/data/forgero/packs/edenring/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#1065 [Patch]: Bow gametests for 1.20
  fabric/forgero-fabric-core/src/test/java/com/sigmundgranaas/forgero/fabric/gametest/BowTest.java
  fabric/forgero-fabric-core/src/test/resources/fabric.mod.json
Labels: testing

#969 [Patch]: Fixed on-hit not applying feature conditions
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/initialization/ForgeroPreInit.java
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/EntityTickHandlerMixin.java
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/LivingEntitySwingHandMixin.java
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/OnEntityHitMixin.java
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/PlayerInteractionManagerMixin.java
  fabric/forgero-fabric-core/src/main/java/com/sigmundgranaas/forgero/fabric/mixins/PlayerServerInteractionManagerMixin.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/feature/onhit/block/OnHitBlockFeature.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/feature/onhit/block/OnHitBlockFeatureExecutor.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/feature/onhit/entity/OnHitEntityFeature.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/feature/onhit/entity/OnHitEntityFeatureExecutor.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/feature/swinghand/SwingHandFeature.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/feature/swinghand/SwingHandFeatureExecutor.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/feature/tick/EntityTickFeature.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/feature/tick/EntityTickFeatureExecutor.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/handler/entity/EntityBasedHandler.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/handler/use/BaseHandler.java
  fabric/minecraft-common/src/main/java/com/sigmundgranaas/forgero/minecraft/common/handler/use/ThrowableItem.java
  fabric/minecraft-common/src/test/java/com/sigmundgranaas/forgero/minecraft/common/feature/EntityTickExecutorTest.java
  fabric/minecraft-common/src/test/java/com/sigmundgranaas/forgero/minecraft/common/feature/SwingHandFeatureExecutorTest.java
  fabric/minecraft-common/src/test/java/com/sigmundgranaas/forgero/minecraft/common/feature/onhit/entity/OnHitBlockFeatureExecutorTest.java
  fabric/minecraft-common/src/test/java/com/sigmundgranaas/forgero/minecraft/common/feature/onhit/entity/OnHitEntityFeatureExecutorTest.java
  fabric/modules/bows/src/main/java/com/sigmundgranaas/forgero/bow/entity/DynamicArrowEntity.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/property/v2/feature/BasePredicateData.java
  forgero-core/src/main/java/com/sigmundgranaas/forgero/core/util/match/MatchContext.java
Labels: bug
