Repository SigmundGranaas/forgero, pull requests merged in 2024-07, with the labels that each got.

#934 [Patch]: Test fixes for buildscript
  build.gradle
  fabric/build.gradle
  fabric/forgero-fabric-compat/build.gradle
  fabric/forgero-fabric-core/build.gradle
  fabric/gradle.properties
  fabric/modules/build.gradle
Labels: enhancement, code quality, important

#946 Ecologics compatibility has been added.
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/azalea.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/coconut.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/flowering_azalea.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/seashell.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/walnut.png
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/azalea.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/coconut.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/flowering_azalea.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/seashell.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/walnut.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/package.json
Labels: new feature, texture, compatibility, balancing

#955 [Feature]: 6 materials added for BetterEnd.
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/betterend/enchanted_petal.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/betterend/glowing_bulb.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/betterend/hydralux_petal.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/betterend/lumecorn_rod.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/betterend/silk_moth_matrix.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/betterend/small_jellyshroom.png
  content/forgero-compat/src/main/resources/data/forgero/packs/betterend/material/enchanted_petal.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betterend/material/glowing_bulb.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betterend/material/hydralux_petal.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betterend/material/lumecorn_rod.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betterend/material/silk_moth_matrix.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betterend/material/small_jellyshroom.json
Labels: new feature, texture, compatibility

#960 [Patch]: Fixed betternether compat
  content/forgero-compat/src/main/resources/assets/betternether/models/item/piglin_axe_head-schematic.json
  content/forgero-compat/src/main/resources/assets/betternether/models/item/piglin_hoe_head-schematic.json
  content/forgero-compat/src/main/resources/assets/betternether/models/item/piglin_pickaxe_head-schematic.json
  content/forgero-compat/src/main/resources/assets/betternether/models/item/piglin_pommel-schematic.json
  content/forgero-compat/src/main/resources/assets/betternether/models/item/piglin_shovel_head-schematic.json
  content/forgero-compat/src/main/resources/assets/betternether/models/item/piglin_sword_blade-schematic.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betternether/material/black_vine.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betternether/material/blooming_vine.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betternether/material/golden_vine.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betternether/models/piglin_pommel.json
  content/forgero-compat/src/main/resources/data/forgero/packs/betternether/schematic/piglin_pommel.json
Labels: bug, code quality, compatibility

#982 [Patch]: Remove windows and macos from build actions
  .github/workflows/build_fabric.yml
Labels: ci/cd

#962 [Feature]: Schematic trades for villagers
  fabric/forgero-fabric-compat/build.gradle
  fabric/forgero-fabric-core/build.gradle
  fabric/modules/trade/build.gradle
  fabric/modules/trade/src/main/java/com/sigmundgranaas/forgero/trademodule/TradeInitializer.java
  fabric/modules/trade/src/main/java/com/sigmundgranaas/forgero/trademodule/util/ForgeroCustomTrades.java
  fabric/modules/trade/src/main/resources/assets/forgero/icon.png
  fabric/modules/trade/src/main/resources/fabric.mod.json
  settings.gradle
Labels: new feature, balancing

#981 [Compat]: Added advanced Netherite Compat
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/advancednetherite/netherite_diamond_ingot.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/advancednetherite/netherite_emerald_ingot.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/advancednetherite/netherite_gold_ingot.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/advancednetherite/netherite_iron_ingot.png
  content/forgero-compat/src/main/resources/data/forgero/packs/advancednetherite/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/advancednetherite/material/netherite_diamond_ingot.json
  content/forgero-compat/src/main/resources/data/forgero/packs/advancednetherite/material/netherite_emerald_ingot.json
  content/forgero-compat/src/main/resources/data/forgero/packs/advancednetherite/material/netherite_gold_ingot.json
  content/forgero-compat/src/main/resources/data/forgero/packs/advancednetherite/material/netherite_iron_ingot.json
  content/forgero-compat/src/main/resources/data/forgero/packs/advancednetherite/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#937 [Compat]: Naturalist Compat
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/naturalist/bear_fur.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/naturalist/cattail_fluff.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/naturalist/glow_goop.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/naturalist/shellstone.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/naturalist/snail_shell.png
  content/forgero-compat/src/main/resources/data/forgero/packs/naturalist/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/naturalist/material/bear_fur.json
  content/forgero-compat/src/main/resources/data/forgero/packs/naturalist/material/cattail_fluff.json
  content/forgero-compat/src/main/resources/data/forgero/packs/naturalist/material/glow_goop.json
  content/forgero-compat/src/main/resources/data/forgero/packs/naturalist/material/shellstone.json
  content/forgero-compat/src/main/resources/data/forgero/packs/naturalist/material/snail_shell.json
  content/forgero-compat/src/main/resources/data/forgero/packs/naturalist/package.json
  fabric/build.gradle
  fabric/forgero-fabric-compat/build.gradle
Labels: new feature, texture, compatibility, balancing

#958 [Compat]: Ecologics compat
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/azalea.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/coconut.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/flowering_azalea.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/seashell.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ecologics/walnut.png
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/azalea.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/coconut.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/flowering_azalea.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/seashell.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/material/walnut.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ecologics/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#975 [Compat]: Ad Astra
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ad_astra/calorite.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ad_astra/desh.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ad_astra/ostrum.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/ad_astra/steel.png
  content/forgero-compat/src/main/resources/data/forgero/packs/ad-astra/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ad-astra/material/calorite.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ad-astra/material/desh.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ad-astra/material/ostrum.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ad-astra/material/steel.json
  content/forgero-compat/src/main/resources/data/forgero/packs/ad-astra/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#974 [Compat]: Create compat
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/andesite_alloy.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/asurine.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/brass.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/crimsite.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/limestone.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/ochrum.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/polished_rose_quartz.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/powdered_obsidian.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/scorchia.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/scoria.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/veridium.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/create/zinc.png
  content/forgero-compat/src/main/resources/data/forgero/packs/create/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/andesite_alloy.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/asurine.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/brass.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/crimsite.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/limestone.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/ochrum.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/polished_rose_quartz.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/powdered_obsidian.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/scorchia.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/scoria.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/veridium.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/material/zinc.json
  content/forgero-compat/src/main/resources/data/forgero/packs/create/package.json
  fabric/build.gradle
Labels: new feature, texture, compatibility, balancing

#979 [Compat]: Tech Reborn
  content/forgero-compat/src/main/resources/assets/forgero/lang/en_us.json
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/aluminum.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/brass.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/chromium.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/electrum.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/invar.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/iridium.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/lead.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/nickel.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/advanced_alloy.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/carbon_fiber.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/carbon_mesh.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/peridot.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/red_garnet.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/refined_iron.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/rubber.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/rubber_planks.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/ruby.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/sap.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/sapphire.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/synthetic_redstone.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/tungstensteel.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/techreborn/yellow_garnet.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/titanium.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/tungsten.png
  content/forgero-compat/src/main/resources/assets/forgero/templates/materials/zinc.png
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/aluminum.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/brass.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/bronze.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/chromium.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/electrum.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/invar.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/iridium.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/lead.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/nickel.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/platinum.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/silver.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/steel.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/titanium.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/tungsten.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/material/zinc.json
  content/forgero-compat/src/main/resources/data/forgero/packs/common/package.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/default.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/advanced_alloy.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/carbon_fiber.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/carbon_mesh.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/peridot.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/red_garnet.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/refined_iron.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/rubber.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/rubber_planks.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/ruby.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/sap.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/sapphire.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/synthetic_redstone.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/tungstensteel.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/material/yellow_garnet.json
  content/forgero-compat/src/main/resources/data/forgero/packs/techreborn/package.json
Labels: new feature, texture, compatibility, balancing
